# GoReleaser config

before:
  hooks:
    - go mod tidy

builds:
  - id: tenet_darwin
    binary: tenet
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -tags
      - sqlite

  - id: tenet_linux
    binary: tenet
    env:
      - CGO_ENABLED=1
    flags:
      - -tags
      - sqlite
    goos:
      - linux
    goarch:
      - amd64

  - id: tenet_windows_x64
    binary: tenet
    ldflags:
      - "-extldflags '-static'"
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -tags
      - sqlite
    goos:
      - windows
    goarch:
      - amd64

archives:
  - format_overrides:
      - goos: 'windows'
        format: 'zip'
    files:
      - site_template/**/*
      - config.yml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: 'asc'
  filters:
    exclude: ['^docs:', '^test:', 'Merge pull request', 'Merge branch']
